[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "googlemaps>=4.10.0",
    "openai==1.3.7",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "flask>=2.3.3",
]
